name: Build

on:
  pull_request:
    types: [open, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g C4Builder
      - run: C4Builder

      #- name: C4Builder
      #  uses: clippings/c4builder-action@v1

